package com.example.client;

import com.example.client.com.example.ws.CarService;
import com.example.client.com.example.ws.CarServiceImplService;
import com.example.client.com.example.ws.Car;


public class SoapClient {
    public static void main(String[] args) {
       
         // TODO: use file generated by wsimport to create instance of your service
          CarServiceImplService serviceImpl = new CarServiceImplService();
          CarService carService = serviceImpl.getCarServiceImplPort();
        
         Car car = carService.getCar("11AA22");
         System.out.println("brand:"+car.getBrand()+" price:"+car.getPrice()+"is it runet:"+car.isRented());
         
         //System.out.println(carService.rentCar(""));
         //System.out.println(carService.getBackCar(""));
         
    }
}
