
package com.example.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarService", targetNamespace = "http://ws.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.ws.Car
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.example.com/CarService/getCarRequest", output = "http://ws.example.com/CarService/getCarResponse")
    public Car getCar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.example.com/CarService/rentCarRequest", output = "http://ws.example.com/CarService/rentCarResponse")
    public boolean rentCar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.example.com/CarService/getBackCarRequest", output = "http://ws.example.com/CarService/getBackCarResponse")
    public boolean getBackCar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
